// src/components/projects/ProjectCard.tsx
import GitHubIcon from '@mui/icons-material/GitHub';
import OpenInNewIcon from '@mui/icons-material/OpenInNew';
import {
  Box,
  Button,
  Card,
  CardActions,
  CardContent,
  Chip,
  IconButton,
  Typography,
} from '@mui/material';
import type { ReactElement } from 'react';
import RevealSection from '../common/RevealSection';
import { fonts } from '../../theme';

export interface ProjectLink {
  label: string;
  href: string;
  icon?: ReactElement;
}

export interface Project {
  name: string;
  category: string;
  description: string;
  href: string;
  links?: ProjectLink[];
  tags: string[];
}

export interface ProjectCardProps {
  project: Project;
  rootMargin?: string;
}

export default function ProjectCard({ project, rootMargin }: ProjectCardProps) {
  return (
    <RevealSection rootMargin={rootMargin} sx={{ display: 'flex' }}>
      <Card
        sx={{
          display: 'flex',
          flexDirection: 'column',
          flex: 1,
          overflowWrap: 'anywhere',
          '&:hover': { transform: 'translateY(-4px)', borderColor: 'primary.main' },
          '@media (prefers-reduced-motion: reduce)': { '&:hover': { transform: 'none' } },
        }}
      >
        <CardContent sx={{ flex: 1 }}>
          {/* header: name, category, repo link */}
          <Box
            sx={{
              mb: 1,
              display: 'flex',
              alignItems: 'flex-start',
              justifyContent: 'space-between',
              gap: 2,
            }}
          >
            <Box sx={{ display: 'flex', flexWrap: 'wrap', alignItems: 'center', gap: 1 }}>
              <Typography variant="h3" component="h3" sx={{ fontFamily: fonts.mono }}>
                {project.name}
              </Typography>
              <Chip label={project.category} size="small" color="primary" variant="outlined" />
            </Box>

            <IconButton
              component="a"
              href={project.href}
              target="_blank"
              rel="noreferrer"
              aria-label="View on GitHub"
              size="small"
            >
              <GitHubIcon />
            </IconButton>
          </Box>

          <Typography color="text.secondary">{project.description}</Typography>

          {/* tags */}
          <Box sx={{ mt: 2, display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
            {project.tags.map((tag) => (
              <Chip key={tag} label={tag} size="small" variant="outlined" />
            ))}
          </Box>
        </CardContent>

        {/* external links */}
        {project.links ? (
          <CardActions sx={{ px: 2, pb: 2, gap: 1, flexWrap: 'wrap' }}>
            {project.links.map((link) => (
              <Button
                key={link.href}
                component="a"
                href={link.href}
                target="_blank"
                rel="noreferrer"
                size="small"
                variant="outlined"
                startIcon={link.icon ?? <OpenInNewIcon />}
              >
                {link.label}
              </Button>
            ))}
          </CardActions>
        ) : null}
      </Card>
    </RevealSection>
  );
}

// src/components/projects/ProjectCard.vue
<script setup lang="ts">
import RevealSection from '../common/RevealSection.vue';

export interface ProjectLink {
  label: string;
  href: string;
  icon?: string;
}

export interface Project {
  name: string;
  category: string;
  description: string;
  href: string;
  links?: ProjectLink[];
  tags: string[];
}

defineProps<{
  project: Project;
  rootMargin?: string;
  animationDelay?: string;
}>();
</script>

<template>
  <RevealSection
    :root-margin="rootMargin"
    :style="{ animationDelay }"
    class="card flex min-w-0 flex-col rounded-card border border-border bg-bg-soft p-7 [overflow-wrap:anywhere] hover:border-accent-border hover:shadow-card"
  >
    <!-- header: name, category, repo link -->
    <div class="mb-2 flex items-start justify-between gap-4">
      <div class="flex flex-wrap items-center gap-2">
        <h3 class="m-0 font-mono">{{ project.name }}</h3>
        <span
          class="rounded-full border border-accent-border bg-accent-bg px-[0.55rem] py-[0.2rem] text-[0.7rem] tracking-[0.04em] text-accent uppercase"
        >
          {{ project.category }}
        </span>
      </div>

      <a
        :href="project.href"
        target="_blank"
        rel="noreferrer"
        aria-label="View on GitHub"
        class="text-xl text-text no-underline hover:text-accent"
      >
        <span class="pi pi-github" />
      </a>
    </div>

    <!-- description -->
    <p>{{ project.description }}</p>

    <!-- tags -->
    <ul class="mt-4 mb-4 flex list-none flex-wrap gap-[0.4rem] p-0">
      <li
        v-for="tag in project.tags"
        :key="tag"
        class="rounded-full border border-border bg-bg px-[0.6rem] py-1 text-xs text-text-h"
      >
        {{ tag }}
      </li>
    </ul>

    <!-- external links -->
    <div
      v-if="project.links"
      class="mt-auto flex flex-wrap gap-2 border-t border-dashed border-border pt-4"
    >
      <a
        v-for="link in project.links"
        :key="link.href"
        :href="link.href"
        target="_blank"
        rel="noreferrer"
        class="inline-flex items-center gap-1.5 rounded-full border border-accent-border bg-accent-bg px-[0.7rem] py-1.5 text-sm text-accent no-underline hover:-translate-y-px"
      >
        <span :class="link.icon || 'pi pi-external-link'" />
        <span>{{ link.label }}</span>
      </a>
    </div>
  </RevealSection>
</template>

<style scoped>
.card {
  opacity: 0;
  transform: none;
  transition:
    transform 0.3s ease,
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

.card.is-visible {
  animation: fade-rise 0.5s var(--ease-reveal) both;
}

@keyframes fade-rise {
  from {
    opacity: 0;
    translate: 0 12px;
  }
  to {
    opacity: 1;
    translate: 0 0;
  }
}

.card.is-visible:hover {
  transform: translateY(-4px);
}

@media (prefers-reduced-motion: reduce) {
  .card,
  .card.is-visible {
    animation: none;
    opacity: 1;
    translate: none;
    scale: none;
    transform: none;
  }

  .card.is-visible:hover {
    transform: none;
  }
}
</style>
