// src/pages/HomePage.tsx
import AccountTreeIcon from '@mui/icons-material/AccountTree';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import BarChartIcon from '@mui/icons-material/BarChart';
import BoltIcon from '@mui/icons-material/Bolt';
import CheckCircleIcon from '@mui/icons-material/CheckCircle';
import CloudIcon from '@mui/icons-material/Cloud';
import CodeIcon from '@mui/icons-material/Code';
import DnsIcon from '@mui/icons-material/Dns';
import GitHubIcon from '@mui/icons-material/GitHub';
import Inventory2Icon from '@mui/icons-material/Inventory2';
import KeyboardArrowDownIcon from '@mui/icons-material/KeyboardArrowDown';
import ListIcon from '@mui/icons-material/List';
import LockIcon from '@mui/icons-material/Lock';
import PaletteIcon from '@mui/icons-material/Palette';
import RefreshIcon from '@mui/icons-material/Refresh';
import SettingsIcon from '@mui/icons-material/Settings';
import ShieldIcon from '@mui/icons-material/Shield';
import ShowChartIcon from '@mui/icons-material/ShowChart';
import StorageIcon from '@mui/icons-material/Storage';
import SwapHorizIcon from '@mui/icons-material/SwapHoriz';
import SyncIcon from '@mui/icons-material/Sync';
import WidgetsIcon from '@mui/icons-material/Widgets';
import {
  Avatar,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Container,
  Divider,
  Paper,
  Typography,
} from '@mui/material';
import type { ReactElement } from 'react';
import { Link } from 'react-router';
import HeroTerminal from '../components/common/HeroTerminal';
import PageMeta from '../components/common/PageMeta';
import RevealSection from '../components/common/RevealSection';
import { useScrollReveal } from '../hooks/useScrollReveal';
import { easing, layout, pageSection } from '../theme';

const icons = {
  server: <DnsIcon fontSize="small" />,
  code: <CodeIcon fontSize="small" />,
  bolt: <BoltIcon fontSize="small" />,
  database: <StorageIcon fontSize="small" />,
  component: <WidgetsIcon fontSize="small" />,
  palette: <PaletteIcon fontSize="small" />,
  sync: <SyncIcon fontSize="small" />,
  box: <Inventory2Icon fontSize="small" />,
  cloud: <CloudIcon fontSize="small" />,
  chartLine: <ShowChartIcon fontSize="small" />,
  chartBar: <BarChartIcon fontSize="small" />,
  list: <ListIcon fontSize="small" />,
  shield: <ShieldIcon fontSize="small" />,
  lock: <LockIcon fontSize="small" />,
  gateway: <SwapHorizIcon fontSize="small" />,
  cog: <SettingsIcon fontSize="small" />,
  github: <GitHubIcon fontSize="small" />,
  refresh: <RefreshIcon fontSize="small" />,
  check: <CheckCircleIcon fontSize="small" />,
};

const stack: { name: string; icon: ReactElement }[] = [
  { name: 'Java', icon: icons.server },
  { name: 'TypeScript', icon: icons.code },
  { name: 'Go', icon: icons.bolt },
  { name: 'Python', icon: icons.code },
  { name: 'SQL', icon: icons.database },
  { name: 'Spring Boot', icon: icons.server },
  { name: 'Gin', icon: icons.bolt },
  { name: 'GORM', icon: icons.database },
  { name: 'JPA', icon: icons.database },
  { name: 'React', icon: icons.component },
  { name: 'Angular', icon: icons.code },
  { name: 'Vue 3', icon: icons.code },
  { name: 'Vite', icon: icons.bolt },
  { name: 'PrimeNG', icon: icons.component },
  { name: 'PrimeVue', icon: icons.component },
  { name: 'Material UI', icon: icons.palette },
  { name: 'Tailwind CSS', icon: icons.palette },
  { name: 'PostgreSQL', icon: icons.database },
  { name: 'NATS', icon: icons.sync },
  { name: 'WebSockets', icon: icons.bolt },
  { name: 'Docker', icon: icons.box },
  { name: 'Kubernetes', icon: icons.server },
  { name: 'k3s', icon: icons.server },
  { name: 'Helm', icon: icons.box },
  { name: 'Argo CD', icon: icons.sync },
  { name: 'AWS', icon: icons.cloud },
  { name: 'EKS', icon: icons.server },
  { name: 'EC2', icon: icons.server },
  { name: 'S3', icon: icons.database },
  { name: 'EFS', icon: icons.database },
  { name: 'Lambda', icon: icons.bolt },
  { name: 'DynamoDB', icon: icons.database },
  { name: 'CloudWatch', icon: icons.chartLine },
  { name: 'CloudFormation', icon: icons.cloud },
  { name: 'Jenkins', icon: icons.cog },
  { name: 'GitHub Actions', icon: icons.github },
  { name: 'Renovate', icon: icons.refresh },
  { name: 'Karate', icon: icons.check },
  { name: 'Datadog', icon: icons.chartLine },
  { name: 'Prometheus', icon: icons.chartLine },
  { name: 'Grafana', icon: icons.chartBar },
  { name: 'Loki', icon: icons.list },
  { name: 'Dex', icon: icons.shield },
  { name: 'Sealed Secrets', icon: icons.lock },
  { name: 'Envoy Gateway', icon: icons.gateway },
  { name: 'Cloudflare', icon: icons.cloud },
  { name: 'Bash', icon: icons.code },
];

const highlights = [
  {
    title: 'Full-stack engineering',
    body: 'Java + Spring Boot and Go + Gin services behind Angular and React interfaces, designed, tested, and shipped end to end.',
    icon: <AccountTreeIcon />,
  },
  {
    title: 'Cloud and Kubernetes platforms',
    body: 'Multi-tenant developer platforms on AWS and EKS, with Spring Boot APIs orchestrating Kubernetes workloads for thousands of users.',
    icon: <DnsIcon />,
  },
  {
    title: 'Real-time and self-hosted systems',
    body: 'A production k3s cluster fronted by Envoy Gateway, with Dex federated sign-in, highly available PostgreSQL, and NATS pub/sub for horizontally scaled WebSocket broadcasting, delivered continuously through Argo CD GitOps.',
    icon: <BoltIcon />,
  },
];

// keeps the h1 available to screen readers and crawlers without showing it
const visuallyHidden = {
  position: 'absolute',
  width: 1,
  height: 1,
  overflow: 'hidden',
  clip: 'rect(0 0 0 0)',
  whiteSpace: 'nowrap',
} as const;

export default function HomePage() {
  const chips = useScrollReveal<HTMLDivElement>();

  return (
    <Box>
      <PageMeta
        title="Max Morhardt – Software Engineer"
        description="Max Morhardt is a Full Stack Engineer at Fidelity Investments specializing in Java, Spring Boot, Go, TypeScript, React, Angular, Kubernetes, and AWS."
        canonical="https://maxstash.io/"
      />

      {/* hero */}
      <Box
        component="section"
        sx={{
          position: 'relative',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          overflow: 'hidden',
          minHeight: `calc(100svh - ${layout.headerHeight.lg})`,
          py: { xs: 3, md: 6 },
        }}
      >
        {/* ambient background glows */}
        <Box aria-hidden sx={{ pointerEvents: 'none', position: 'absolute', inset: 0 }}>
          {[
            { size: 520, bg: 'heroGlow1', pos: { top: -120, left: -120 }, speed: '12s' },
            { size: 460, bg: 'heroGlow2', pos: { bottom: -160, right: -120 }, speed: '14s' },
          ].map((glow) => (
            <Box
              key={glow.bg}
              sx={{
                position: 'absolute',
                ...glow.pos,
                width: glow.size,
                height: glow.size,
                borderRadius: '50%',
                filter: 'blur(100px)',
                opacity: 0.7,
                bgcolor: glow.bg,
                animation: `float ${glow.speed} ease-in-out infinite`,
                '@keyframes float': {
                  '0%, 100%': { transform: 'translate(0, 0)' },
                  '50%': { transform: 'translate(40px, 30px)' },
                },
                '@media (prefers-reduced-motion: reduce)': { animation: 'none' },
              }}
            />
          ))}
        </Box>

        <Container
          maxWidth="lg"
          sx={{ position: 'relative', display: 'flex', justifyContent: 'center' }}
        >
          <Typography variant="h1" sx={visuallyHidden}>
            Max Morhardt, Software Engineer
          </Typography>

          <RevealSection sx={{ display: 'flex', width: '100%', justifyContent: 'center' }}>
            <HeroTerminal />
          </RevealSection>
        </Container>

        {/* scroll affordance */}
        <Box
          aria-hidden
          sx={{
            position: 'absolute',
            bottom: 24,
            left: '50%',
            color: 'text.secondary',
            opacity: 0.5,
            display: { xs: 'none', md: 'block' },
            animation: 'bounce 2.4s ease-in-out infinite',
            '@keyframes bounce': {
              '0%, 100%': { transform: 'translate(-50%, 0)' },
              '50%': { transform: 'translate(-50%, 8px)' },
            },
            '@media (prefers-reduced-motion: reduce)': {
              animation: 'none',
              transform: 'translateX(-50%)',
            },
          }}
        >
          <KeyboardArrowDownIcon />
        </Box>
      </Box>

      {/* highlights */}
      <Divider />
      <Box component="section" sx={{ ...pageSection, bgcolor: 'background.paper' }}>
        <Container maxWidth="lg">
          <RevealSection>
            <Typography variant="h2" align="center" gutterBottom>
              What I do
            </Typography>
          </RevealSection>

          <RevealSection delay={1}>
            <Typography
              align="center"
              color="text.secondary"
              sx={{ mx: 'auto', mb: 6, maxWidth: '56ch' }}
            >
              A few areas where I spend most of my engineering time.
            </Typography>
          </RevealSection>

          <Box sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 2.5 }}>
            {highlights.map((h, i) => (
              <RevealSection
                key={h.title}
                delay={(i + 1) as 1 | 2 | 3}
                variant="rise"
                sx={{ display: 'flex', minWidth: 0, maxWidth: 360, flex: '1 1 280px' }}
              >
                <Card
                  sx={{
                    flex: 1,
                    bgcolor: 'background.default',
                    '&:hover': { transform: 'translateY(-4px)', borderColor: 'primary.main' },
                    '@media (prefers-reduced-motion: reduce)': { '&:hover': { transform: 'none' } },
                  }}
                >
                  <CardContent>
                    <Avatar
                      variant="rounded"
                      sx={{ mb: 2, bgcolor: 'action.hover', color: 'primary.main' }}
                    >
                      {h.icon}
                    </Avatar>
                    <Typography variant="h3" component="h3" gutterBottom>
                      {h.title}
                    </Typography>
                    <Typography color="text.secondary">{h.body}</Typography>
                  </CardContent>
                </Card>
              </RevealSection>
            ))}
          </Box>
        </Container>
      </Box>
      <Divider />

      {/* stack chips */}
      <Box component="section" sx={pageSection}>
        <Container maxWidth="lg">
          <RevealSection>
            <Typography variant="h2" align="center" gutterBottom>
              Tools of the trade
            </Typography>
          </RevealSection>

          <RevealSection delay={1}>
            <Typography
              align="center"
              color="text.secondary"
              sx={{ mx: 'auto', mb: 6, maxWidth: '56ch' }}
            >
              Day-to-day languages, frameworks, and platforms.
            </Typography>
          </RevealSection>

          <Box
            ref={chips.ref}
            sx={{ display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: 1 }}
          >
            {stack.map((item, i) => (
              <Chip
                key={item.name}
                icon={item.icon}
                label={item.name}
                variant="outlined"
                sx={{
                  // chips stagger in once the row scrolls into view
                  opacity: 0,
                  ...(chips.visible && {
                    animation: `chip-reveal 0.4s ${easing.reveal} both`,
                    animationDelay: `${i * 45}ms`,
                  }),
                  '@keyframes chip-reveal': {
                    from: { opacity: 0, transform: 'translateY(12px)' },
                    to: { opacity: 1, transform: 'none' },
                  },
                  '&:hover': { borderColor: 'primary.main', color: 'primary.main' },
                  '@media (prefers-reduced-motion: reduce)': { opacity: 1, animation: 'none' },
                }}
              />
            ))}
          </Box>
        </Container>
      </Box>

      {/* editorial statement: a heading/body spread, deliberately not a card grid */}
      <Divider />
      <Box component="section" sx={{ ...pageSection, bgcolor: 'background.paper' }}>
        <Container maxWidth="lg">
          <Box
            sx={{
              display: 'grid',
              gap: { xs: 3, md: 6 },
              gridTemplateColumns: { md: '13rem 1fr' },
              alignItems: 'start',
            }}
          >
            <RevealSection>
              <Typography variant="h3" component="h2">
                How I work
              </Typography>
            </RevealSection>

            <RevealSection
              delay={1}
              sx={{
                borderLeft: { md: 2 },
                borderColor: { md: 'primary.main' },
                pl: { md: 4 },
              }}
            >
              <Typography
                sx={{
                  fontSize: 'clamp(1.3rem, 2.4vw, 1.8rem)',
                  fontWeight: 500,
                  lineHeight: 1.45,
                  color: 'text.primary',
                }}
              >
                At Fidelity, I build multi-tenant developer platforms end to end:{' '}
                <Box component="em" sx={{ fontStyle: 'normal', color: 'primary.main' }}>
                  Spring Boot services and Angular interfaces
                </Box>
                , built and deployed to EKS through Jenkins pipelines for thousands of engineers.
              </Typography>

              <Typography color="text.secondary" sx={{ mt: 2.5, fontSize: '1.1rem' }}>
                Beyond that, I self-host every app on this site on a Kubernetes cluster I run and
                maintain myself.
              </Typography>
            </RevealSection>
          </Box>
        </Container>
      </Box>
      <Divider />

      {/* cta */}
      <Box component="section" sx={pageSection}>
        <Container maxWidth="lg">
          <RevealSection variant="rise">
            <Paper
              sx={{
                display: 'flex',
                flexDirection: 'column',
                alignItems: 'center',
                gap: 2,
                textAlign: 'center',
                py: 7,
                px: 4,
                bgcolor: 'background.paper',
              }}
            >
              <Typography variant="h2">Let&apos;s build something.</Typography>

              <Typography color="text.secondary" sx={{ maxWidth: '46ch' }}>
                Have a project in mind, or just want to say hi? My inbox is open.
              </Typography>

              <Box
                sx={{
                  mt: 2,
                  display: 'flex',
                  flexWrap: 'wrap',
                  justifyContent: 'center',
                  gap: 1.5,
                }}
              >
                <Button
                  component={Link}
                  to="/contact"
                  variant="contained"
                  size="large"
                  endIcon={<ArrowForwardIcon />}
                >
                  Get in touch
                </Button>

                <Button component={Link} to="/projects" variant="outlined" size="large">
                  See the projects
                </Button>
              </Box>
            </Paper>
          </RevealSection>
        </Container>
      </Box>
    </Box>
  );
}

// src/pages/HomePage.vue
<script setup lang="ts">
import { useRouter } from 'vue-router';
import { RouterLink } from 'vue-router';
import RevealSection from '../components/common/RevealSection.vue';
import HeroTerminal from '../components/common/HeroTerminal.vue';
import { usePageMeta } from '../composables/usePageMeta';
import { useScrollReveal } from '../composables/useScrollReveal';

usePageMeta({
  title: 'Max Morhardt – Software Engineer',
  description:
    'Max Morhardt is a Full Stack Engineer at Fidelity Investments specializing in Java, Spring Boot, Go, TypeScript, React, Angular, Kubernetes, and AWS.',
  canonical: 'https://maxstash.io/',
});

const router = useRouter();

const { target: chipsTarget, visible: chipsVisible } = useScrollReveal<HTMLDivElement>();

const stack = [
  { name: 'Java', icon: 'pi pi-server' },
  { name: 'TypeScript', icon: 'pi pi-code' },
  { name: 'Go', icon: 'pi pi-bolt' },
  { name: 'Python', icon: 'pi pi-code' },
  { name: 'SQL', icon: 'pi pi-database' },
  { name: 'Spring Boot', icon: 'pi pi-server' },
  { name: 'Gin', icon: 'pi pi-bolt' },
  { name: 'GORM', icon: 'pi pi-database' },
  { name: 'JPA', icon: 'pi pi-database' },
  { name: 'React', icon: 'pi pi-prime' },
  { name: 'Angular', icon: 'pi pi-code' },
  { name: 'Vue 3', icon: 'pi pi-code' },
  { name: 'Vite', icon: 'pi pi-bolt' },
  { name: 'PrimeNG', icon: 'pi pi-prime' },
  { name: 'PrimeVue', icon: 'pi pi-prime' },
  { name: 'Material UI', icon: 'pi pi-palette' },
  { name: 'Tailwind CSS', icon: 'pi pi-palette' },
  { name: 'PostgreSQL', icon: 'pi pi-database' },
  { name: 'NATS', icon: 'pi pi-sync' },
  { name: 'WebSockets', icon: 'pi pi-bolt' },
  { name: 'Docker', icon: 'pi pi-box' },
  { name: 'Kubernetes', icon: 'pi pi-server' },
  { name: 'k3s', icon: 'pi pi-server' },
  { name: 'Helm', icon: 'pi pi-box' },
  { name: 'Argo CD', icon: 'pi pi-sync' },
  { name: 'AWS', icon: 'pi pi-cloud' },
  { name: 'EKS', icon: 'pi pi-server' },
  { name: 'EC2', icon: 'pi pi-server' },
  { name: 'S3', icon: 'pi pi-database' },
  { name: 'EFS', icon: 'pi pi-database' },
  { name: 'Lambda', icon: 'pi pi-bolt' },
  { name: 'DynamoDB', icon: 'pi pi-database' },
  { name: 'CloudWatch', icon: 'pi pi-chart-line' },
  { name: 'CloudFormation', icon: 'pi pi-cloud' },
  { name: 'Jenkins', icon: 'pi pi-cog' },
  { name: 'GitHub Actions', icon: 'pi pi-github' },
  { name: 'Renovate', icon: 'pi pi-refresh' },
  { name: 'Karate', icon: 'pi pi-check-circle' },
  { name: 'Datadog', icon: 'pi pi-chart-line' },
  { name: 'Prometheus', icon: 'pi pi-chart-line' },
  { name: 'Grafana', icon: 'pi pi-chart-bar' },
  { name: 'Loki', icon: 'pi pi-list' },
  { name: 'Dex', icon: 'pi pi-shield' },
  { name: 'Sealed Secrets', icon: 'pi pi-lock' },
  { name: 'Envoy Gateway', icon: 'pi pi-arrow-right-arrow-left' },
  { name: 'Cloudflare', icon: 'pi pi-cloud' },
  { name: 'Bash', icon: 'pi pi-code' },
];

const highlights = [
  {
    title: 'Full-stack engineering',
    body: 'Java + Spring Boot and Go + Gin services behind Angular and React interfaces, designed, tested, and shipped end to end.',
    icon: 'pi pi-sitemap',
  },
  {
    title: 'Cloud and Kubernetes platforms',
    body: 'Multi-tenant developer platforms on AWS and EKS, with Spring Boot APIs orchestrating Kubernetes workloads for thousands of users.',
    icon: 'pi pi-server',
  },
  {
    title: 'Real-time and self-hosted systems',
    body: 'A production k3s cluster fronted by Envoy Gateway, with Dex federated sign-in, highly available PostgreSQL, and NATS pub/sub for horizontally scaled WebSocket broadcasting, delivered continuously through Argo CD GitOps.',
    icon: 'pi pi-bolt',
  },
];
</script>

<template>
  <div class="w-full">
    <!-- hero -->
    <section
      class="relative box-border flex min-h-[calc(100svh-var(--header-h))] w-full items-center justify-center overflow-hidden pt-6 pb-18 max-[880px]:pt-4 max-[880px]:pb-6"
    >
      <div class="pointer-events-none absolute inset-0" aria-hidden="true">
        <div class="glow glow--1" />
        <div class="glow glow--2" />
      </div>
      <div class="layout-container relative flex w-full justify-center">
        <h1 class="sr-only">Max Morhardt, Software Engineer</h1>
        <RevealSection class="flex w-full justify-center">
          <HeroTerminal />
        </RevealSection>
      </div>
      <div class="hero-scroll max-[880px]:hidden" aria-hidden="true">
        <span class="pi pi-chevron-down" />
      </div>
    </section>

    <!-- highlights -->
    <section class="layout-section w-full border-y border-border bg-bg-soft">
      <div class="layout-container">
        <RevealSection as="h2" class="text-center">What I do</RevealSection>
        <RevealSection :delay="1" as="p" class="mx-auto mb-12 max-w-[56ch] text-center text-text">
          A few areas where I spend most of my engineering time.
        </RevealSection>
        <div class="flex flex-wrap justify-center gap-5">
          <RevealSection
            v-for="(h, i) in highlights"
            :key="h.title"
            :delay="(i + 1) as 1 | 2 | 3"
            class="lift-card reveal--rise min-w-0 max-w-[360px] flex-[1_1_280px] rounded-card border border-border bg-bg p-7 hover:border-accent-border hover:shadow-card"
          >
            <div
              class="mb-4 inline-flex size-11 items-center justify-center rounded-[10px] bg-accent-bg text-xl text-accent"
            >
              <span :class="h.icon" />
            </div>
            <h3>{{ h.title }}</h3>
            <p>{{ h.body }}</p>
          </RevealSection>
        </div>
      </div>
    </section>

    <!-- stack chips -->
    <section class="layout-section w-full">
      <div class="layout-container">
        <RevealSection as="h2" class="text-center">Tools of the trade</RevealSection>
        <RevealSection :delay="1" as="p" class="mx-auto mb-12 max-w-[56ch] text-center text-text">
          Day-to-day languages, frameworks, and platforms.
        </RevealSection>
        <div
          :ref="(el: unknown) => (chipsTarget = el as HTMLDivElement | null)"
          class="chips flex flex-wrap justify-center gap-[0.6rem]"
          :class="{ 'is-visible': chipsVisible }"
        >
          <span
            v-for="(item, i) in stack"
            :key="item.name"
            class="chip inline-flex items-center gap-2 rounded-full border border-border bg-bg-soft px-4 py-[0.55rem] text-[0.95rem] text-text-h transition-[border-color,color] duration-200 ease-out hover:border-accent-border hover:text-accent"
            :style="{ animationDelay: `${i * 45}ms` }"
          >
            <span :class="item.icon" />
            <span>{{ item.name }}</span>
          </span>
        </div>
      </div>
    </section>

    <!-- editorial statement: a heading/body spread, deliberately not a card grid -->
    <section class="layout-section w-full border-y border-border bg-bg-soft">
      <div class="layout-container">
        <div class="statement-grid">
          <RevealSection as="h2" class="statement-label">How I work</RevealSection>
          <RevealSection :delay="1" as="div" class="statement-body">
            <p class="statement-lead">
              At Fidelity, I build multi-tenant developer platforms end to end:
              <em>Spring Boot services and Angular interfaces</em>, built and deployed to EKS
              through Jenkins pipelines for thousands of engineers.
            </p>
            <p class="statement-sub">
              Beyond that, I self-host every app on this site on a Kubernetes cluster I run and
              maintain myself.
            </p>
          </RevealSection>
        </div>
      </div>
    </section>

    <!-- cta -->
    <section class="layout-section w-full">
      <div class="layout-container">
        <RevealSection class="cta-panel reveal--rise flex flex-col items-center gap-4 text-center">
          <h2 class="m-0">Let's build something.</h2>
          <p class="max-w-[46ch] text-text">
            Have a project in mind, or just want to say hi? My inbox is open.
          </p>
          <div class="mt-4 flex flex-wrap items-center justify-center gap-3">
            <button class="cta-primary" @click="router.push('/contact')">
              <span>Get in touch</span>
              <span class="pi pi-arrow-right text-[0.85rem]" />
            </button>
            <RouterLink to="/projects" class="cta-ghost">
              <span>See the projects</span>
            </RouterLink>
          </div>
        </RevealSection>
      </div>
    </section>
  </div>
</template>

<style scoped>
.glow {
  position: absolute;
  border-radius: 50%;
  filter: blur(100px);
  opacity: 0.7;
}

.glow--1 {
  width: 520px;
  height: 520px;
  top: -120px;
  left: -120px;
  background: var(--hero-glow-1);
  animation: float 12s ease-in-out infinite;
}

.glow--2 {
  width: 460px;
  height: 460px;
  bottom: -160px;
  right: -120px;
  background: var(--hero-glow-2);
  animation: float 14s ease-in-out infinite reverse;
}

@keyframes float {
  0%,
  100% {
    transform: translate(0, 0);
  }
  50% {
    transform: translate(40px, 30px);
  }
}

.hero-scroll {
  position: absolute;
  bottom: 1.5rem;
  left: 50%;
  transform: translateX(-50%);
  font-size: 1.5rem;
  color: var(--text);
  opacity: 0.5;
  animation: bounce 2.4s ease-in-out infinite;
}

@keyframes bounce {
  0%,
  100% {
    transform: translate(-50%, 0);
  }
  50% {
    transform: translate(-50%, 8px);
  }
}

.lift-card {
  transition:
    opacity 1.3s var(--ease-reveal),
    transform 1.3s var(--ease-reveal),
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

.lift-card:hover {
  transform: translateY(-4px);
  transition:
    transform 0.3s ease,
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

/* editorial statement: a heading/body spread that fills the container width */
.statement-grid {
  display: grid;
  gap: 1.5rem 3rem;
}

@media (min-width: 860px) {
  .statement-grid {
    grid-template-columns: 13rem 1fr;
    align-items: start;
  }
}

.statement-label {
  margin: 0;
  font-size: clamp(1.35rem, 2.2vw, 1.7rem);
  font-weight: 600;
  color: var(--text-h);
}

.statement-body {
  border-left: 2px solid var(--accent-border);
  padding-left: 2rem;
}

@media (max-width: 859px) {
  .statement-body {
    border-left: none;
    padding-left: 0;
  }
}

.statement-lead {
  font-size: clamp(1.3rem, 2.4vw, 1.8rem);
  font-weight: 500;
  line-height: 1.45;
  letter-spacing: -0.01em;
  color: var(--text-h);
}

.statement-lead em {
  font-style: normal;
  color: var(--accent);
}

.statement-sub {
  margin-top: 1.25rem;
  font-size: clamp(1rem, 1.4vw, 1.15rem);
  line-height: 1.6;
  color: var(--text);
}

@media (max-width: 640px) {
  .statement {
    padding-left: 1.1rem;
  }
}

/* closing cta panel: clean surface, no gradient or glow */
.cta-panel {
  padding: 3.5rem 2rem;
  border-radius: var(--radius-panel);
  border: 1px solid var(--border);
  background: var(--bg-soft);
}

.cta-primary,
.cta-ghost {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  border-radius: 999px;
  font-size: 0.95rem;
  font-weight: 500;
  cursor: pointer;
  text-decoration: none;
  transition:
    transform 0.2s ease,
    border-color 0.2s ease,
    background 0.2s ease,
    color 0.2s ease,
    filter 0.2s ease;
}

.cta-primary {
  border: 1px solid var(--accent);
  background: var(--accent);
  color: #fff;
}

.cta-primary:hover {
  transform: translateY(-2px);
  filter: brightness(1.08);
}

.cta-ghost {
  border: 1px solid var(--border);
  background: var(--bg);
  color: var(--text-h);
}

.cta-ghost:hover {
  transform: translateY(-2px);
  border-color: var(--accent-border);
  background: var(--accent-bg);
  color: var(--accent);
}

@media (prefers-reduced-motion: reduce) {
  .cta-primary:hover,
  .cta-ghost:hover {
    transform: none;
  }
}

/* chips stagger in via inline animation-delay once the row scrolls into view */
.chip {
  opacity: 0;
  transform: translateY(12px);
}

@keyframes chip-reveal {
  from {
    opacity: 0;
    transform: translateY(12px);
  }
  to {
    opacity: 1;
    transform: translateY(0);
  }
}

.chips.is-visible .chip {
  animation: chip-reveal 0.4s var(--ease-reveal) both;
}

@media (prefers-reduced-motion: reduce) {
  .chip,
  .chips.is-visible .chip {
    opacity: 1;
    transform: none;
    animation: none;
  }
}
</style>
