// src/components/contact/ContactCard.tsx
import NorthEastIcon from '@mui/icons-material/NorthEast';
import { Avatar, Box, Card, CardActionArea, Typography } from '@mui/material';
import type { ReactNode } from 'react';
import RevealSection from '../common/RevealSection';

export interface ContactChannel {
  label: string;
  href: string;
  icon: ReactNode;
  handle: string;
}

export interface ContactCardProps {
  channel: ContactChannel;
  delay?: 0 | 1 | 2 | 3 | 4;
}

export default function ContactCard({ channel, delay }: ContactCardProps) {
  return (
    <RevealSection
      delay={delay}
      variant="scale"
      sx={{ minWidth: 0, maxWidth: 400, flex: '1 1 280px', display: 'flex' }}
    >
      <Card
        sx={{
          flex: 1,
          '&:hover': { transform: 'translateY(-4px)', borderColor: 'primary.main' },
          '&:hover .contact-card__arrow': { opacity: 1, color: 'primary.main' },
          '@media (prefers-reduced-motion: reduce)': { '&:hover': { transform: 'none' } },
        }}
      >
        <CardActionArea
          component="a"
          href={channel.href}
          target="_blank"
          rel="noreferrer"
          sx={{ display: 'flex', alignItems: 'center', gap: 2, p: 3 }}
        >
          <Avatar variant="rounded" sx={{ bgcolor: 'action.hover', color: 'text.primary' }}>
            {channel.icon}
          </Avatar>

          <Box sx={{ minWidth: 0, flex: 1, overflowWrap: 'anywhere' }}>
            <Typography sx={{ fontWeight: 600, color: 'text.primary' }}>{channel.label}</Typography>
            <Typography variant="body2" color="text.secondary">
              {channel.handle}
            </Typography>
          </Box>

          <NorthEastIcon
            className="contact-card__arrow"
            fontSize="small"
            sx={{ color: 'text.secondary', opacity: 0.5, transition: 'opacity 0.2s, color 0.2s' }}
          />
        </CardActionArea>
      </Card>
    </RevealSection>
  );
}

// src/components/contact/ContactCard.vue
<script setup lang="ts">
import RevealSection from '../common/RevealSection.vue';

export interface ContactChannel {
  label: string;
  href: string;
  icon: string;
  handle: string;
}

defineProps<{
  channel: ContactChannel;
  delay?: 0 | 1 | 2 | 3 | 4;
}>();
</script>

<template>
  <RevealSection
    :delay="delay"
    class="card reveal--scale min-w-0 max-w-[400px] flex-[1_1_280px] rounded-card border border-border bg-bg-soft hover:border-accent-border hover:shadow-card"
  >
    <a
      :href="channel.href"
      target="_blank"
      rel="noreferrer"
      class="card__link flex min-w-0 items-center gap-4 p-6 text-text-h no-underline max-[600px]:p-4"
    >
      <!-- channel icon -->
      <span
        class="inline-flex size-11 shrink-0 items-center justify-center rounded-[10px] border border-border bg-bg text-text-h"
      >
        <span class="text-xl" :class="channel.icon" />
      </span>

      <!-- label + handle -->
      <span
        class="flex min-w-0 flex-1 flex-col break-words text-[0.9rem] text-text [overflow-wrap:anywhere]"
      >
        <strong class="text-base text-text-h">{{ channel.label }}</strong>
        <span>{{ channel.handle }}</span>
      </span>

      <!-- hover arrow -->
      <span
        class="pi pi-arrow-up-right card__arrow text-text opacity-50 transition-[opacity,transform,color] duration-200 ease-out"
      />
    </a>
  </RevealSection>
</template>

<style scoped>
.card {
  transition:
    transform 0.3s ease,
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

.card.reveal {
  transition:
    opacity 0.8s var(--ease-spring),
    transform 0.8s var(--ease-spring),
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

.card:hover {
  transform: translateY(-4px);
  transition:
    transform 0.3s ease,
    border-color 0.3s ease,
    box-shadow 0.3s ease;
}

.card:hover .card__arrow {
  opacity: 1;
  transform: translate(2px, -2px);
  color: var(--accent);
}
</style>
