// src/components/common/LegalPage.vue
<script setup lang="ts">
export interface LegalSection {
  title: string;
  content: string | string[];
}

defineProps<{
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
}>();
</script>

<template>
  <section class="layout-section pt-12">
    <div class="mx-auto box-border w-full max-w-[760px] px-6">
      <!-- heading -->
      <h1 class="page-title">{{ title }}</h1>
      <p class="mb-10 text-text opacity-70">Last updated: {{ lastUpdated }}</p>

      <!-- sections -->
      <div v-for="section in sections" :key="section.title" class="mb-8">
        <h2 class="mb-2 text-[1.15rem]">{{ section.title }}</h2>

        <!-- lead paragraph plus optional bullet list -->
        <template v-if="Array.isArray(section.content)">
          <p v-if="section.content.length > 0" class="leading-[1.7] text-text">
            {{ section.content[0] }}
          </p>
          <ul v-if="section.content.length > 1" class="mt-2 mb-0 list-disc pl-5">
            <li
              v-for="item in section.content.slice(1)"
              :key="item"
              class="leading-[1.7] text-text"
            >
              {{ item }}
            </li>
          </ul>
        </template>

        <!-- single paragraph -->
        <p v-else class="leading-[1.7] text-text">{{ section.content }}</p>
      </div>
    </div>
  </section>
</template>

// src/components/common/LegalPage.tsx
import { Box, Container, List, ListItem, ListItemText, Typography } from '@mui/material';
import { layout, pageSection } from '../../theme';

export interface LegalSection {
  title: string;
  content: string | string[];
}

export interface LegalPageProps {
  title: string;
  lastUpdated: string;
  sections: LegalSection[];
}

export default function LegalPage({ title, lastUpdated, sections }: LegalPageProps) {
  return (
    <Box component="section" sx={pageSection}>
      <Container sx={{ maxWidth: { sm: layout.proseWidth } }}>
        <Typography variant="h4" component="h1" gutterBottom>
          {title}
        </Typography>

        <Typography color="text.secondary" sx={{ mb: 5, opacity: 0.8 }}>
          Last updated: {lastUpdated}
        </Typography>

        {sections.map((section) => (
          <Box key={section.title} sx={{ mb: 4 }}>
            <Typography variant="h3" component="h2" sx={{ mb: 1, fontSize: '1.15rem' }}>
              {section.title}
            </Typography>

            {Array.isArray(section.content) ? (
              <>
                {/* lead paragraph plus optional bullet list */}
                {section.content.length > 0 ? (
                  <Typography color="text.secondary" sx={{ lineHeight: 1.7 }}>
                    {section.content[0]}
                  </Typography>
                ) : null}

                {section.content.length > 1 ? (
                  <List dense sx={{ listStyleType: 'disc', pl: 3, py: 0 }}>
                    {section.content.slice(1).map((item) => (
                      <ListItem key={item} sx={{ display: 'list-item', px: 0, py: 0.25 }}>
                        <ListItemText
                          primary={item}
                          slotProps={{
                            primary: { color: 'text.secondary', sx: { lineHeight: 1.7 } },
                          }}
                        />
                      </ListItem>
                    ))}
                  </List>
                ) : null}
              </>
            ) : (
              <Typography color="text.secondary" sx={{ lineHeight: 1.7 }}>
                {section.content}
              </Typography>
            )}
          </Box>
        ))}
      </Container>
    </Box>
  );
}
