// src/App.tsx
import { Box } from '@mui/material';
import { Outlet } from 'react-router';
import ScrollToTop from './components/common/ScrollToTop';
import AppFooter from './components/footer/AppFooter';
import AppHeader from './components/header/AppHeader';

export default function App() {
  return (
    <>
      <ScrollToTop />

      <Box sx={{ display: 'flex', flexDirection: 'column', minHeight: '100dvh' }}>
        <AppHeader />

        <Box component="main" sx={{ flex: 1 }}>
          <Outlet />
        </Box>

        <AppFooter />
      </Box>
    </>
  );
}

// src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router';
import AppHeader from './components/header/AppHeader.vue';
import AppFooter from './components/footer/AppFooter.vue';
</script>

<template>
  <div class="app">
    <!-- site header / navigation -->
    <AppHeader />

    <!-- routed page content -->
    <main class="app-main">
      <RouterView />
    </main>

    <!-- site footer -->
    <AppFooter />
  </div>
</template>

<style scoped>
.app {
  display: flex;
  flex-direction: column;
  min-height: 100dvh;
}

.app-main {
  flex: 1;
}
</style>
